version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: yoshijyk/vprofiledb
    container_name: vprodb
    ports:
      - 3306:3306
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    container_name: vpromq01
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    container_name: vproapp
    image: yoshijyk/vprofileapp
    ports:
      - "8080:8080"

  vproweb:
    build:
      context: ./Docker-files/web
    container_name: vproweb
    image: yoshijyk/vprofileweb
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}